# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 22:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Chorus'), (0, 'Verse'), (2, 'Break')], default=0)),
                ('content', models.TextField()),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='kyo.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Round')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('number_of_occurences', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Album')),
                ('lyrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Lyrics')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='lyrics',
            field=models.ManyToManyField(through='kyo.WordLyrics', to='kyo.Lyrics'),
        ),
        migrations.AddField(
            model_name='vote',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Word'),
        ),
        migrations.AddField(
            model_name='round',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Song'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyo.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('game', 'player', 'word')]),
        ),
    ]
