# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyo', '0002_auto_20190604_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('name', 'artist')]),
        ),
    ]
