# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyo', '0003_auto_20190604_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlyrics',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kyo.Song'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='kyo.Song'),
        ),
        migrations.AlterField(
            model_name='wordlyrics',
            name='position',
            field=models.IntegerField(),
        ),
    ]
