# Generated by Django 2.2.4 on 2019-08-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyo', '0008_word_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyo.Album'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyo.Game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyo.Song'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kyo.Game'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyo.Round'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyo.Word'),
        ),
    ]
